# Generated by Django 5.2.6 on 2025-09-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('New Arrival', 'New Arrival'), ('Most Popular', 'Most Popular'), ('Trending', 'Trending')], default='new', max_length=20)),
                ('expire', models.DateField()),
                ('stock', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
