# Generated by Django 5.2.6 on 2025-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_catagory_notification_order_list_product_add_sign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='sold',
        ),
        migrations.AddField(
            model_name='product_add',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product_add',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='category',
            field=models.CharField(blank=True, choices=[('New Arrival', 'New Arrival'), ('Most Popular', 'Most Popular'), ('Trending', 'Trending')], default='new', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='expire',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
